version: "3"
services:
  dummy-server:
    build:
      context: "./dummy_server/."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dummy_server:/code
    # entrypoint: ["tail", "-f", "/dev/null"]
